### ISSUE TITLE
rss

### ISSUE THREAD

**Issue by smcclstocks** [jondot/graphene#35]
How's the rss support coming along? It's the only thing keeping me from pulling the trigger

**Comment by jondot** [comment]
Hey there,

I had a wacky implementation which I wasn't happy with running for commit messages for a short while, I found that it clashed with the idea of graphs and I dismissed it entirely.

Since most people didn't ask about RSS, it kind of went down in priority for me -- however I'd gladly accept a pull request or/and help with a candidate implementation. 

In either case I'd love to learn about your use case, this stuff is fascinating for me :)

Feel free to describe it as you see fit, a couple of lines, a screenshot of what you would like to have had, etc.

**Comment by smcclstocks** [comment]
Firstly, I'm not a UI guy lol so bummer.

But what I was thinking is a configurable RSS feed aggregator where I can display the most recent N number of feeds. My first implementation would be to use the RSS feed from gitweb to display most recent activity in a particular repo. Basically something like "so & so changed repo foo with commit log of bar". At a glance we can see exactly what changed inline with critical metrics. &/Or I was thinking about having a git hook that generated a JSON document in couchdb for every commit & accessing that JSON document out of couchdb as a widget too.

https://gist.github.com/1306223

Whichever is easier I suppose. Couchdb is nice because I use it as a messaging bus for all sorts of things so would be cool to have an arbitrary JSON widget to stream such documents. What do you think?

**Comment by jondot** [comment]
This use case is something I tested for a short period of time on Graphene.

What I didn't take into account is that it was too small for a dash TV and people wouldn't take that much interest with it given that they already have plenty notifications from Github.

What I ended up doing is this project (which you could use):

https://github.com/jondot/dash

With it, I could have a dedicated screen for burst-type messages. One stream of those messages were commit messages. A single message stays on screen until another one replaces it so it is big and gives plenty of time to read.

You can hook the generic Github webhook out of the box or use the method you suggested with Couchdb.

Either case if you still need this kind of thing in Graphene - I'm open to accepting a pull request.
