### ISSUE TITLE
Graphene <-> Redis Store communication

### ISSUE THREAD

**Issue by ssuryawa** [jondot/graphene#39]
Hi,

I'm new to Graphene & want to fetch data for Graphene from Redis store. Can anyone please help me on any documentation/links/steps on how to achieve this.

Thanks in advance.
## 

Shailendra...

**Comment by jondot** [comment]
Hi,

Graphene is built to plug with anything that looks like a Graphite data source.

If you want to use Redis, then I'm assuming you have a service that serves the Redis data somewhere.
And also, since Redis is not a time-series store naturally, I'm also assuming you took the effort to build a time-series model abstraction over Redis.

If you can shape the time-series data from your service into how Graphite shapes it - you should have no problem at 
all just placing a link to your data service instead of the Graphite link.

As a quick example, this is how Graphite renders the time-series as JSON:

```
[{"target": "some.metric", "datapoints": [[3328437.8333333335, 1358255100], [3328653.1666666665, 1358255160], [3328835.0, 1358255220], [3328978.1666666665, 1358255280], [3329080.5, 1358255340], [3329199.6666666665, 1358255400]]}]
```

Hope this helps.

**Comment by jondot** [comment]
Hey, @ssuryawa, just following up - did this help eventually?

**Comment by ssuryawa** [comment]
Hi @jondot, yes, it did help me...I ended up with Statsd -> Graphite -> Graphene...

Thanks...

**Comment by jondot** [comment]
That's great, happy to hear
