### ISSUE TITLE
Number of labels not increasing!

### ISSUE THREAD

**Issue by saurabhmenon** [jondot/graphene#65]
2: {
      source: "http://0.0.0.0.:8080/render?from=03%3A00_20130625&until=03%3A30_20130625&width=400&height=250&target=trialfinal.bugg.vks&target=trialfinal.bugg.ov&target=trialfinal.bugg.total&target=trialfinal.bugg.mr&target=trialfinal.bugg.as&target=trialfinal.bugg.vk&uniq=0.0689613800495863&format=json",
      TimeSeries: {
        title: 'title',
        num_labels: 'six',
        //parent: '#g1-2'
      }
        }
thats my code but the num_labels does not seem to work even if i try a number, say, 6. now there are lines on my graph that are unexplained. it shows only three.

**Comment by jondot** [comment]
Hi,
`num_labels` is should be a number, and it is actually the maximal number of labels to show, when you are trying to render several time series on one graphs.

This means that in order to include more graphs, either add another `target` or use a glob like `servers.fooserver.cpu.*`. The labels will generate automatically.
